### PR TITLE
Update Asset Pack (Alternative Logos)

### PR DESCRIPTION
**Pull request by MilesRJohnson**
The aim of this PR is to update the alternative logos in the asset pack. The feet on the alternative logos are not the same shape (see images below).

__Before__

Screen Shot 2019-10-28 at 11 45 35

Screen Shot 2019-10-28 at 12 44 41

__After__

Screen Shot 2019-10-28 at 13 04 03

### CODE REVIEW

**Comment by dmontrose** [comment]
Re needing to sort this – is there a reason we didn't just open the regular logo, invert the colours and save back out? Two minute job…?

**Comment by MilesRJohnson** [comment]
@dmontrose This is what happened. It was not a two minute job, as there are multiple file types for each logo type (horizontal, vertical, etc.) and after each type is exported it then needs to be optimized for size (particularly the SVG files) and then of course a PR needs to be opened, reviewed, and merged.

**Comment by dmontrose** [comment]
@MilesRJohnson – apologies – but maybe 10 minutes for the files updates? I just opened an original logo, changed the colours and exported as three files types in a minute. Resizing shouldn't need doing if it's based off regular logo files. Just making sure you're not creating extra work for yourself if things like this are taking a while.

**Comment by MilesRJohnson** [comment]
@dmontrose Ok.

**Pull request merged**
