### PR TITLE
Add logo to readme

### PR DESCRIPTION
**Pull request by iwz**
Ironically, the presskit readme didn't contain the thoughtbot logo.

### CODE REVIEW

**Comment by tysongach** [comment]
Is it weird having the word “thoughtbot” right above the logo that says “thoughtbot”?

**Comment by iwz** [comment]
yes. thoughts on how to resolve?

**Comment by smharley** [comment]
Maybe something like this?

image

**Comment by iwz** [comment]
PTAL @smharley @tysongach

**Pull request merged**
