### PR TITLE
SVG logo optimization and accessibility

### PR DESCRIPTION
**Pull request by tysongach**
- Improve SVG accessibility
  - Add `title` and `desc`
  - Add ARIA attributes
- Optimize SVG (with [svgo](https://github.com/svg/svgo))
  - Reduction of 18.6%

If we like this change, I’ll do the same to the remaining SVG logo files.

cc: @brendastorer @whmii @ckundo

### CODE REVIEW

**Comment by whmii** [comment]
:+1:

**Comment by ckundo** [comment]
@tysongach

**Comment by tysongach** [comment]
Updated with the rest of the logos.

**Comment by whmii** [comment]
As a note, I don't think that the optimization here is a necessary addition. These are/should be art files not necessarily production files. IMHO

**Comment by tysongach** [comment]
@whmii Yeah, I debated that. But I've seen people linking directly to them for production purposes…not sure if this is a good or bad thing.

**Comment by brendastorer** [comment]
Should the description maybe indicate that they are logos?

**Comment by ckundo** [comment]
Is the logo purely decorative? If so, it should probably be marked up as presentational (I think `role="presentation` is valid, but double check).

**Comment by whmii** [comment]
I would say that a logo (aka circle with robot) *is* purely decorative, but a wordmark is not.

**Comment by tysongach** [comment]
Updated: I needed to add `role="img"`, which exposes the meta information to screen readers; doing this allowed Safari to read aloud the `title` and `desc`. The screenshots below show what the screen reader was saying (the second image, which is where it exposes the `desc` happens when you stay on the image for a few seconds):

screen shot 2015-08-30 at 4 18 50 pm

screen shot 2015-08-30 at 4 18 13 pm

**Comment by ckundo** [comment]
LGTM

**Pull request merged**
